-- MySQL Script generated by MySQL Workbench
-- Mon Oct 23 15:05:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema animacion_db
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema animacion_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `animacion_db` ;

-- -----------------------------------------------------
-- Schema animacion_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `animacion_db` DEFAULT CHARACTER SET utf8 ;
USE `animacion_db` ;

-- -----------------------------------------------------
-- Table `animacion_db`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `animacion_db`.`categoria` ;

CREATE TABLE IF NOT EXISTS `animacion_db`.`categoria` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(250) NULL DEFAULT NULL,
  `eliminado` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `animacion_db`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `animacion_db`.`producto` ;

CREATE TABLE IF NOT EXISTS `animacion_db`.`producto` (
  `id_producto` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATETIME NULL DEFAULT NULL,
  `fecha_actualizacion` DATETIME NULL DEFAULT NULL,
  `eliminado` TINYINT(4) NULL DEFAULT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(250) NULL DEFAULT NULL,
  `precio` DECIMAL(6,2) NOT NULL,
  `id_categoria` INT(11) NOT NULL,
  PRIMARY KEY (`id_producto`),
  CONSTRAINT `fk_Producto_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `animacion_db`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `animacion_db`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `animacion_db`.`rol` ;

CREATE TABLE IF NOT EXISTS `animacion_db`.`rol` (
  `id_rol` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `eliminado` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `animacion_db`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `animacion_db`.`usuario` ;

CREATE TABLE IF NOT EXISTS `animacion_db`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATETIME NULL DEFAULT NULL,
  `fecha_actualizacion` DATETIME NULL DEFAULT NULL,
  `eliminado` TINYINT(4) NULL DEFAULT 0,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `apellido` VARCHAR(50) NULL DEFAULT NULL,
  `ci` VARCHAR(10) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `celular` VARCHAR(45) NULL DEFAULT NULL,
  `id_rol` INT(11) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `fk_Usuario_rol1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `animacion_db`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `animacion_db`.`paquete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `animacion_db`.`paquete` ;

CREATE TABLE IF NOT EXISTS `animacion_db`.`paquete` (
  `id_paquete` INT NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATETIME NULL,
  `fecha_actualizacion` DATETIME NULL,
  `eliminado` TINYINT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `precio` DECIMAL(6,2) NULL,
  `img` VARCHAR(45) NULL,
  `categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id_paquete`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animacion_db`.`detalle_paquete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `animacion_db`.`detalle_paquete` ;

CREATE TABLE IF NOT EXISTS `animacion_db`.`detalle_paquete` (
  `id_producto` INT(11) NOT NULL,
  `id_paquete` INT NOT NULL,
  `cantidad` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `importe` VARCHAR(45) NULL,
  PRIMARY KEY (`id_producto`, `id_paquete`),
  CONSTRAINT `fk_producto_has_paquete_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `animacion_db`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_paquete_paquete1`
    FOREIGN KEY (`id_paquete`)
    REFERENCES `animacion_db`.`paquete` (`id_paquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `animacion_db`.`comprobante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `animacion_db`.`comprobante` ;

CREATE TABLE IF NOT EXISTS `animacion_db`.`comprobante` (
  `id_comprobante` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `cantidad` INT NULL,
  `serie` VARCHAR(45) NULL,
  PRIMARY KEY (`id_comprobante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animacion_db`.`reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `animacion_db`.`reserva` ;

CREATE TABLE IF NOT EXISTS `animacion_db`.`reserva` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATETIME NULL,
  `fecha_actualizacion` DATETIME NULL,
  `eliminado` TINYINT NULL,
  `fecha_evento` DATETIME NULL,
  `direccion_evento` VARCHAR(45) NULL,
  `contacto` VARCHAR(45) NULL,
  `img_comprobante` VARCHAR(45) NULL,
  `pagado` TINYINT NULL,
  `total` DECIMAL(6,2) NULL,
  `serie` VARCHAR(45) NULL,
  `num_documento` VARCHAR(45) NULL,
  `id_comprobante` INT NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `id_cliente` INT(11) NULL,
  `id_paquete` INT NOT NULL,
  PRIMARY KEY (`id_reserva`),
  CONSTRAINT `fk_reserva_comprobante1`
    FOREIGN KEY (`id_comprobante`)
    REFERENCES `animacion_db`.`comprobante` (`id_comprobante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `animacion_db`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_paquete1`
    FOREIGN KEY (`id_paquete`)
    REFERENCES `animacion_db`.`paquete` (`id_paquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `animacion_db`.`personalizado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `animacion_db`.`personalizado` ;

CREATE TABLE IF NOT EXISTS `animacion_db`.`personalizado` (
  `producto_id_producto` INT(11) NOT NULL,
  `reserva_id_reserva` INT NOT NULL,
  PRIMARY KEY (`producto_id_producto`, `reserva_id_reserva`),
  CONSTRAINT `fk_producto_has_reserva_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `animacion_db`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_reserva_reserva1`
    FOREIGN KEY (`reserva_id_reserva`)
    REFERENCES `animacion_db`.`reserva` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
